import React, { useState } from 'react';
import { Copy, Check, Download, Layers, ShieldCheck } from 'lucide-react';

export const GitIgnoreGeneratorTool: React.FC = () => {
  const [selectedStacks, setSelectedStacks] = useState<string[]>(['node', 'react', 'vscode', 'macos']);
  const [copied, setCopied] = useState<boolean>(false);

  const presets: { id: string; name: string; content: string }[] = [
    {
      id: 'node',
      name: 'Node.js & npm',
      content: `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Build output
dist/
build/
out/`
    },
    {
      id: 'react',
      name: 'React / Next.js',
      content: `# Next.js build
.next/
out/

# Production build artifacts
dist/
build/

# Next.js telemetry
.next/telemetry/`
    },
    {
      id: 'python',
      name: 'Python',
      content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/

# Virtual Environments
.env
.venv
env/
venv/
ENV/`
    },
    {
      id: 'rust',
      name: 'Rust & Cargo',
      content: `# Generated by Cargo
target/

# Cargo.lock is typically tracked for binaries, untracked for libraries
# Cargo.lock`
    },
    {
      id: 'go',
      name: 'Golang',
      content: `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with 'go test -c'
*.test

# Output of the go coverage tool
*.out`
    },
    {
      id: 'vscode',
      name: 'Visual Studio Code',
      content: `.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace`
    },
    {
      id: 'macos',
      name: 'macOS (.DS_Store)',
      content: `.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes`
    },
    {
      id: 'env',
      name: 'Environment & Secrets (.env)',
      content: `# Local Environment Files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
*.pem
*.key`
    }
  ];

  const toggleStack = (id: string) => {
    setSelectedStacks(prev => 
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  const generatedContent = selectedStacks
    .map(id => {
      const p = presets.find(x => x.id === id);
      return p ? `### ${p.name} ###\n${p.content}\n` : '';
    })
    .join('\n');

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.gitignore';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Multi-select Tags */}
      <div className="p-4 bg-slate-900/80 rounded-2xl border border-slate-800 space-y-2.5">
        <span className="text-xs font-semibold text-white block">Select Frameworks &amp; Environments</span>
        <div className="flex flex-wrap gap-2">
          {presets.map((p) => {
            const isSelected = selectedStacks.includes(p.id);
            return (
              <button
                key={p.id}
                onClick={() => toggleStack(p.id)}
                className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
                  isSelected
                    ? 'bg-indigo-600 text-white shadow-sm shadow-indigo-600/20'
                    : 'bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800'
                }`}
              >
                {isSelected ? '✓ ' : '+ '} {p.name}
              </button>
            );
          })}
        </div>
      </div>

      {/* Output Viewer */}
      <div className="space-y-2">
        <div className="flex items-center justify-between text-xs text-slate-400 px-1">
          <span>Generated .gitignore ({selectedStacks.length} presets active)</span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="text-indigo-400 hover:text-indigo-300 flex items-center gap-1 font-semibold"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 flex items-center gap-1"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        <pre className="p-4 rounded-2xl bg-slate-950 border border-slate-800 font-mono text-xs text-slate-200 overflow-x-auto max-h-80 leading-relaxed selection:bg-indigo-500">
          {generatedContent || '# Select at least one framework above'}
        </pre>
      </div>
    </div>
  );
};
